### PR TITLE
Rewrite metabolic_pthwy_gocams_count_mf_roots.rq to improve performance

### PR DESCRIPTION
**Pull request by balhoff**

### CODE REVIEW

**Comment by kltm** [comment]
Noting that I finally stopped the current version after two days. This PR took 45 seconds mimicking prod. Seems to be an improvement on the current journal.

**Comment by kltm** [comment]
https://github.com/geneontology/sparql-for-pathway-go-cams/issues/3

**Comment by kltm** [comment]
Merging, as @balhoff is now getting the same number of results.

**Review by dustine32 — APPROVED** [review]
@balhoff @sierra-moxon @kltm Sorry for the delay in checking this out. I was able to run this to produce the same 251 line list from the last `snapshot` journal and it only took about 10 sec. I also spot-checked some of the listed models and confirmed they meet our "metabolic pathway" criteria.

Thanks again so much @balhoff!

**Pull request merged**
